### ISSUE TITLE
hide buttons that are state transitions that are not allowed

### ISSUE THREAD

**Issue by clelange** [clelange/PixelTCDSSupervisor#10]
Have a look at TCDS PDF file, and hide transitions that are not allowed. Also add an "expert action" button to display all buttons that are hidden/not visible.

**Comment by luannd** [comment]
Need to verify before closing :)

**Comment by clelange** [comment]
When in configured, kill PixelTCDSSupervisor, then start it again, and make sure the initialise button is enabled again. Should be the case for any state, since the state of the PixelTCDSSupervisor is "Initial".

**Comment by clelange** [comment]
also, when I click "Reset", the Initialize button does not get enabled, instead, the "Halt" button is enabled, but it should not be the case
