### ISSUE TITLE
display hwCfgString_ in a window

### ISSUE THREAD

**Issue by clelange** [clelange/PixelTCDSSupervisor#8]
see ![image](https://cloud.githubusercontent.com/assets/5270053/16050259/45c54dbe-325b-11e6-9b24-8ad821c3887c.png)

where it is called configuration received.

**Comment by clelange** [comment]
When using the Expert Actions tab, sending new file, try using:

```
/afs/cern.ch/user/c/clange/public/setupRoot.sh
```

You need to catch all the "

**Comment by luannd** [comment]
I'm done

**Comment by clelange** [comment]
make configuration window as wide as the table (two columns)
