### ISSUE TITLE
create application status tab

### ISSUE THREAD

**Issue by clelange** [clelange/PixelTCDSSupervisor#9]
should look like 
![image](https://cloud.githubusercontent.com/assets/5270053/16050476/1498d28c-325c-11e6-9878-21c6bc67662b.png)

Should contain history of commands and up-time, last time updated, current time etc.

**Comment by luannd** [comment]
I have already designed the UI. 
Need for the content

**Comment by luannd** [comment]
need function for uptime, last update etc.

**Comment by clelange** [comment]
The uptime can be termined like this:

  // Update the uptime estimate and the timestamp of the latest
  // monitoring update.
  toolbox::TimeVal timeNow(toolbox::TimeVal::gettimeofday());
  toolbox::TimeInterval upTime = timeNow - timeStart_;

Then, more as a reminder to me (i.e. you can ignore it for now), one can use this as InfoSpace:

  getOwnerApplication()->appStateInfoSpace_.setDouble("upTime",
                                                      double(upTime),
                                                      true);
  getOwnerApplication()->appStateInfoSpace_.setDouble("latestMonitoringUpdate",
                                                      double(timeNow),
                                                      true);
